name: IaC Scan

# Trigger the workflow on pushes to `main` and pull requests
on:
  push:
    branches: [ "main" ]
    paths:
      - 'iac-scanning/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'iac-scanning/**'

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Scan the IaC files in iac-scanning folder with Sysdig Secure
      - name: Sysdig Secure IaC scan
        uses: sysdiglabs/scan-action@v6
        with:
          sysdig-secure-url: https://us2.app.sysdig.com
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          mode: iac
          iac-scan-path: iac-scanning
          recursive: true
#          use-policies: "\"All Posture Findings\""
