name: Build, Push & Scan Quarkus Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: quay.io
  IMAGE_REPO: maratsal/getting-started

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Build the container image with the official Red Hat s2i-build Action.
      # This installs the latest s2i CLI for us automatically.
      - name: Build Quarkus image with s2i
        id: build
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: './getting-started'
          builder_image: registry.access.redhat.com/ubi8/openjdk-17:1.21-1.1751400628
          image: ${{ env.IMAGE_REPO }}
          tags: "${{ github.sha }}"

      # Log in to Quay so we can push both tags.
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # Scan built image
      - name: Sysdig Secure image scan
        uses: sysdiglabs/scan-action@v6
        with:
          sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          image-tag: ${{ env.IMAGE_REPO }}:${{ github.sha }}
          sysdig-secure-url: https://us2.app.sysdig.com

      - name: Push image to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
