name: Build, Push & Scan Quarkus Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  REGISTRY: quay.io
  IMAGE_REPO: maratsal/getting-started

jobs:
  build-push-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Build the container image with the official Red Hat s2i-build Action.
      # This installs the latest s2i CLI for us automatically.
      - name: Build Quarkus image with s2i
        id: build
        uses: redhat-actions/s2i-build@v2
        with:
          path_context: './getting-started'
          builder_image: quay.io/quarkus/ubi-quarkus-graalvmce-s2i:latest
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}
          tags: "${{ github.sha }}"

      # Log in to Quay so we can push both tags.
      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Push image to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      # Scan the freshly pushed commit-specific tag in Sysdig Secure.
      - name: Sysdig Secure image scan
        uses: sysdiglabs/scan-action@v6
        with:
          sysdig_secure_token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_REPO }}:${{ github.sha }}
          fail_on_critical: true
